# Exception Testing 

  
assertThrows 메소드는 총 3개가 존재한다 
![스크린샷 2023-09-06 오후 3 48 55](https://github.com/5selny/5selny.github.io/assets/115622936/71a71ebe-eb71-4f1e-adc1-a3f78c75c925)

assertThrows의 기본 사용법은 람다식 안에 Exception을 Throw하는 작업을 수행하면 된다. 

- assertThrows()
- 2가지 예외 테스트 방법
  - 모두 assertThrows() 메서드를 사용하여 구현할 수 있다
    - 발생한 예외의 세부 사항을 확인
   ![스크린샷 2023-09-06 오후 3 57 59](https://github.com/5selny/5selny.github.io/assets/115622936/d5ce2ccc-5b84-4e5e-a572-ff2b0a264549)

    - 예외 유형의 유효성을 검사
      ![스크린샷 2023-09-06 오후 3 58 47](https://github.com/5selny/5selny.github.io/assets/115622936/14281193-1953-4c8e-abcc-41027bf727ba)

